<a href="https://colab.research.google.com/github/abinmaria/Deep_learning/blob/main/Sentiment_Analysis(RNN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [ ]:
!pip install keras

In [ ]:
!pip install tensorflow

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(oov_token='<nothing>')
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']  # Replace with your actual data
tokenizer.fit_on_texts(docs)
print(len(tokenizer.word_index))


18


In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

**padding**

In [ ]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding


In [ ]:

# Define the model
model = Sequential()

# Add an Embedding layer
model.add(Embedding(input_dim=18, output_dim=2, input_length=5))

# Build the model to ensure it's correctly configured
model.build(input_shape=(None, 5))

# Display the model summary
model.summary()



Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)              │ (None, 5, 2)                │              36 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 36 (144.00 B)

 Trainable params: 36 (144.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile('adam','accuracy')

In [ ]:
sequences = sequences - 1

pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
[[[-0.01739799 -0.00959998]
  [-0.04150696 -0.04826111]
  [-0.00483776 -0.0218944 ]
  [-0.00483776 -0.0218944 ]
  [-0.00483776 -0.0218944 ]]

 [[-0.04150696 -0.04826111]
  [-0.04150696 -0.04826111]
  [-0.00483776 -0.0218944 ]
  [-0.00483776 -0.0218944 ]
  [-0.00483776 -0.0218944 ]]

 [[ 0.04240299 -0.04095409]
  [ 0.04240299 -0.04095409]
  [-0.02238914  0.01846104]
  [-0.00483776 -0.0218944 ]
  [-0.00483776 -0.0218944 ]]

 [[-0.04044665 -0.01977947]
  [-0.0082858   0.00108558]
  [-0.04044665 -0.01977947]
  [-0.04150696 -0.04826111]
  [-0.04044665 -0.01977947]]

 [[ 0.04797607 -0.02170354]
  [-0.03873786 -0.02456282]
  [-0.02523556  0.01085378]
  [-0.04700518  0.00117428]
  [-0.00483776 -0.0218944 ]]

 [[ 0.00846306 -0.01647172]
  [ 0.00846306 -0.01647172]
  [-0.00483776 -0.0218944 ]
  [-0.00483776 -0.0218944 ]
  [-0.00483776 -0.0218944 ]]

 [[ 0.03330842  0.04957904]
  [ 0.03330842  0.04957904]
  [-0.00483776 -0.0218944 ]
  [-0.00483776 -0.0218944 

In [ ]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Flatten


In [ ]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 1s 0us/step


In [ ]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [ ]:
X_train.shape

(25000, 50)

In [ ]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

# Manually build the model by providing an input shape
model.build(input_shape=(None, 50))

model.summary()


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)              │ (None, 50, 2)               │          20,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_2 (SimpleRNN)             │ (None, 32)                  │           1,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.datasets import imdb

# Load the dataset
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)

# No need for further tokenization since IMDB is already tokenized with indices in range [0, 10000)

# Pad sequences to ensure they all have the same length
X_train = pad_sequences(X_train, maxlen=50, padding='post')
X_test = pad_sequences(X_test, maxlen=50, padding='post')

# Build and compile the model
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

# Train the model
history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))


Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 18ms/step - acc: 0.5544 - loss: 0.6755 - val_acc: 0.7822 - val_loss: 0.4611
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 21s 19ms/step - acc: 0.8239 - loss: 0.3992 - val_acc: 0.8098 - val_loss: 0.4183
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 19s 17ms/step - acc: 0.8742 - loss: 0.3144 - val_acc: 0.8064 - val_loss: 0.4361
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - acc: 0.8964 - loss: 0.2624 - val_acc: 0.8022 - val_loss: 0.4371
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 17ms/step - acc: 0.9088 - loss: 0.2413 - val_acc: 0.8031 - val_loss: 0.4681
